charges = [
    'Parken auf einem unbeschilderten Radweg',
    'Parken auf einem Fußgängerüberweg',
    'Parken auf einem Radweg (Zeichen 237)',
    'Parken auf einem Geh- und Radweg (Zeichen 240/241)',
    'Parken auf einer Fahrradstraße (Zeichen 244.1/244.2)',
    'Parken verbotswidrig auf einem Schutzstreifen für den Radverkehr (Zeichen 340)',
    'Parken verbotswidrig auf einem Gehweg',
    'Parken in einem verkehrsberuhigten Bereich (Zeichen 325.1, 325.2) verbotswidrig außerhalb der zum Parken gekennzeichneten Flächen',
    'Parken in einem Fußgängerbereich, der (durch Zeichen 239/242.1, 242.2/250) gesperrt war',
    'Parken in einem Abstand von weniger als 5 Meter vor einem Fußgängerüberweg',
    'Parken weniger als 8 Meter vor der Kreuzung/Einmündung, obwohl in Fahrtrichtung rechts neben der Fahrbahn ein Radweg baulich angelegt ist',
    'Parken weniger als 5 Meter vor/hinter der Kreuzung/Einmündung',
    'Parken im absolutem Haltverbot (Zeichen 283)',
    'Parken unzulässig im eingeschränkten Haltverbot (Zeichen 286)',
    'Parken unzulässig auf einer Sperrfläche (Zeichen 298)',
    'Parken an einer engen/unübersichtlichen Straßenstelle',
    'Parken im Bereich einer scharfen Kurve',
    'Parken unzulässig in der zweiten Reihe',
    'Parken näher als 10 Meter vor einem Lichtzeichen',
    'Parken vor oder in einer amtlich gekennzeichneten Feuerwehrzufahrt',
    'Parken verbotswidrig im Bereich eines Taxenstandes (Zeichen 229)',
    'Parken verbotswidrig und verhinderten dadurch die Benutzung gekennzeichneter Parkflächen',
    'Parken im Bereich einer Grundstückseinfahrt bzw. -ausfahrt',
    'Parken auf einer schmalen Fahrbahn gegenüber einer Grundstückseinfahrt/Grundstücks-ausfahrt',
    'Parken vor einer Bordsteinabsenkung',
    'Parken verbotswidrig auf der linken Fahrbahnseite/dem linken Seitenstreifen',
    'Parken nicht am rechten Fahrbahnrand',
    'Parken im Fahrraum von Schienenfahrzeugen',
    'Parken links von einer Fahrbahnbegrenzung (Zeichen 295)',
    'Parken in einem Verkehrsbereich, der (durch Zeichen 250/251/253/255/260) gesperrt war',
    'Parken auf einem durch Richtungspfeile (Zeichen 297) gekennzeichneten Fahrbahnteil',
    'Parken innerhalb einer Grenzmarkierung (Zeichen 299) für ein Haltverbot',
    'Parken näher als 10 Meter vor einem Andreaskreuz (Zeichen 201)/Zeichen 205 (Vorfahrt gewähren!)/Zeichen 206 (Halt! Vorfahrt gewähren!) und verdeckten dieses',
    'Parken innerhalb eines Kreisverkehrs (Zeichen 215)',
    'Parken in einem Abstand von weniger als 15 Metern von einem Haltestellenschild',
    'Parken, obwohl zwischen Ihrem Fahrzeug und der Fahrstreifenbegrenzung (Zeichen 295/296) ein Abstand von weniger als 3 Metern verblieb',
    'Parken innerhalb einer Grenzmarkierung (Zeichen 299) für ein Parkverbot',
    'Parken bei zulässigem Gehwegparken (Zeichen 315) nicht auf dem Gehweg',
    'Parken auf einem Sonderfahrstreifen für Omnibusse des Linienverkehrs (Zeichen 245)',
    'Parken auf einem gekennzeichneten Behindertenparkplatz',
    'Parken mit Verbrenner vor Elektroladesäule',
    'Parken auf einer Grünfläche',
    'Parken auf einer Baumscheibe',
    'Parken in der Einbahnstraße entgegen der Fahrtrichtung',
    'Sonstiges Parkvergehen (siehe Hinweise)',
]

colormap = {
    'Parken auf einem unbeschilderten Radweg': '#ffcc34',
    'Parken auf einem Fußgängerüberweg': '#5a3de8',
    'Parken auf einem Radweg (Zeichen 237)': '#59ff63',
    'Parken auf einem Geh- und Radweg (Zeichen 240/241)': '#c352ff',
    'Parken auf einer Fahrradstraße (Zeichen 244.1/244.2)': '#74b800',
    'Parken verbotswidrig auf einem Schutzstreifen für den Radverkehr (Zeichen 340)': '#b900b4',
    'Parken verbotswidrig auf einem Gehweg': '#e1ff62',
    'Parken in einem verkehrsberuhigten Bereich (Zeichen 325.1, 325.2) verbotswidrig außerhalb der zum Parken gekennzeichneten Flächen': '#002494',
    'Parken in einem Fußgängerbereich, der (durch Zeichen 239/242.1, 242.2/250) gesperrt war': '#b49700',
    'Parken in einem Abstand von weniger als 5 Meter vor einem Fußgängerüberweg': '#3375ff',
    'Parken weniger als 8 Meter vor der Kreuzung/Einmündung, obwohl in Fahrtrichtung rechts neben der Fahrbahn ein Radweg baulich angelegt ist': '#428000',
    'Parken weniger als 5 Meter vor/hinter der Kreuzung/Einmündung': '#2f0066',
    'Parken im absolutem Haltverbot (Zeichen 283)': '#7fffbd',
    'Parken unzulässig im eingeschränkten Haltverbot (Zeichen 286)': '#fd0039',
    'Parken unzulässig auf einer Sperrfläche (Zeichen 298)': '#41f7ff',
    'Parken an einer engen/unübersichtlichen Straßenstelle': '#d50086',
    'Parken im Bereich einer scharfen Kurve': '#01c1b8',
    'Parken unzulässig in der zweiten Reihe': '#cd005c',
    'Parken näher als 10 Meter vor einem Lichtzeichen': '#96f5ff',
    'Parken vor oder in einer amtlich gekennzeichneten Feuerwehrzufahrt': '#e26700',
    'Parken verbotswidrig im Bereich eines Taxenstandes (Zeichen 229)': '#018dea',
    'Parken verbotswidrig und verhinderten dadurch die Benutzung gekennzeichneter Parkflächen': '#ff9e46',
    'Parken im Bereich einer Grundstückseinfahrt bzw. -ausfahrt': '#01458e',
    'Parken auf einer schmalen Fahrbahn gegenüber einer Grundstückseinfahrt/Grundstücks-ausfahrt': '#ceffd1',
    'Parken vor einer Bordsteinabsenkung': '#7c0076',
    'Parken verbotswidrig auf der linken Fahrbahnseite/dem linken Seitenstreifen': '#f7ffe9',
    'Parken nicht am rechten Fahrbahnrand': '#020025',
    'Parken im Fahrraum von Schienenfahrzeugen': '#efdeff',
    'Parken links von einer Fahrbahnbegrenzung (Zeichen 295)': '#112f00',
    'Parken in einem Verkehrsbereich, der (durch Zeichen 250/251/253/255/260) gesperrt war': '#ff88ed',
    'Parken auf einem durch Richtungspfeile (Zeichen 297) gekennzeichneten Fahrbahnteil': '#005d45',
    'Parken innerhalb einer Grenzmarkierung (Zeichen 299) für ein Haltverbot': '#a39bff',
    'Parken näher als 10 Meter vor einem Andreaskreuz (Zeichen 201)/Zeichen 205 (Vorfahrt gewähren!)/Zeichen 206 (Halt! Vorfahrt gewähren!) und verdeckten dieses': '#7c3000',
    'Parken innerhalb eines Kreisverkehrs (Zeichen 215)': '#008ac7',
    'Parken in einem Abstand von weniger als 15 Metern von einem Haltestellenschild': '#4a3a00',
    'Parken, obwohl zwischen Ihrem Fahrzeug und der Fahrstreifenbegrenzung (Zeichen 295/296) ein Abstand von weniger als 3 Metern verblieb': '#d2b3ff',
    'Parken innerhalb einer Grenzmarkierung (Zeichen 299) für ein Parkverbot': '#211d00',
    'Parken bei zulässigem Gehwegparken (Zeichen 315) nicht auf dem Gehweg': '#ffbcef',
    'Parken auf einem Sonderfahrstreifen für Omnibusse des Linienverkehrs (Zeichen 245)': '#2c002c',
    'Parken auf einem gekennzeichneten Behindertenparkplatz': '#ff9d8c',
    'Parken mit Verbrenner vor Elektroladesäule': '#003a49',
    'Parken auf einer Grünfläche': '#ffc1db',
    'Parken auf einer Baumscheibe': '#5e001d',
    'Parken in der Einbahnstraße entgegen der Fahrtrichtung': '#017896',
    'Sonstiges Parkvergehen (siehe Hinweise)': '#017175',
}

wegli_mapping = {
    'Parken auf einem unbeschilderten Radweg': [],
    'Parken auf einem Fußgängerüberweg': [],
    'Parken auf einem Radweg (Zeichen 237)': ['Parken auf Radfahrstreifen (Verkehrszeichen 237)',
                                              'Parken auf Radfahrstreifen'],
    'Parken auf einem Geh- und Radweg (Zeichen 240/241)': [],
    'Parken auf einer Fahrradstraße (Zeichen 244.1/244.2)': [],
    'Parken verbotswidrig auf einem Schutzstreifen für den Radverkehr (Zeichen 340)': [
        'Parken auf Fahrradschutzstreifen (Gestrichelte Linie)', 'Parken auf Fahrradschutzstreifen'],
    'Parken verbotswidrig auf einem Gehweg': ['Parken auf dem Gehweg'],
    'Parken in einem verkehrsberuhigten Bereich (Zeichen 325.1, 325.2) verbotswidrig außerhalb der zum Parken gekennzeichneten Flächen': [
        'Parken im verkehrsberuhigten Bereich'],
    'Parken in einem Fußgängerbereich, der (durch Zeichen 239/242.1, 242.2/250) gesperrt war': [],
    'Parken in einem Abstand von weniger als 5 Meter vor einem Fußgängerüberweg': [
        'Parken auf dem Fußgängerüberweg sowie 5 Meter davor und dahinter'],
    'Parken weniger als 8 Meter vor der Kreuzung/Einmündung, obwohl in Fahrtrichtung rechts neben der Fahrbahn ein Radweg baulich angelegt ist': [],
    'Parken weniger als 5 Meter vor/hinter der Kreuzung/Einmündung': [
        'Parken im Kreuzungs-/Einmündungsbereich sowie 5 Meter davor und dahinter',
        'Parken im Kreuzungs-/ Einmündungsbereich sowie 5 Meter davor und dahinter'],
    'Parken im absolutem Haltverbot (Zeichen 283)': ['Parken im Halteverbot'],
    'Parken unzulässig im eingeschränkten Haltverbot (Zeichen 286)': [],
    'Parken unzulässig auf einer Sperrfläche (Zeichen 298)': ['Parken auf Sperrflächen'],
    'Parken an einer engen/unübersichtlichen Straßenstelle': [],
    'Parken im Bereich einer scharfen Kurve': [],
    'Parken unzulässig in der zweiten Reihe': ['Parken in zweiter Reihe'],
    'Parken näher als 10 Meter vor einem Lichtzeichen': ['Parken bis zu zehn Meter vor Lichtzeichen',
                                                         'Parken bis zu 10 Meter vor Lichtzeichen',
                                                         'Parkten näher als 10 Meter vor einem Lichtzeichen', ],
    'Parken vor oder in einer amtlich gekennzeichneten Feuerwehrzufahrt': ['Parken vor Feuerwehrzufahrten', ],
    'Parken verbotswidrig im Bereich eines Taxenstandes (Zeichen 229)': [],
    'Parken verbotswidrig und verhinderten dadurch die Benutzung gekennzeichneter Parkflächen': [],
    'Parken im Bereich einer Grundstückseinfahrt bzw. -ausfahrt': ['Parken vor Grundstücksein- und -ausfahrten'],
    'Parken auf einer schmalen Fahrbahn gegenüber einer Grundstückseinfahrt/Grundstücks-ausfahrt': [],
    'Parken vor einer Bordsteinabsenkung': ['Parken vor abgesenkten Bordsteinen'],
    'Parken verbotswidrig auf der linken Fahrbahnseite/dem linken Seitenstreifen': [],
    'Parken nicht am rechten Fahrbahnrand': [],
    'Parken im Fahrraum von Schienenfahrzeugen': [],
    'Parken links von einer Fahrbahnbegrenzung (Zeichen 295)': [],
    'Parken in einem Verkehrsbereich, der (durch Zeichen 250/251/253/255/260) gesperrt war': [],
    'Parken auf einem durch Richtungspfeile (Zeichen 297) gekennzeichneten Fahrbahnteil': [],
    'Parken innerhalb einer Grenzmarkierung (Zeichen 299) für ein Haltverbot': [],
    'Parken näher als 10 Meter vor einem Andreaskreuz (Zeichen 201)/Zeichen 205 (Vorfahrt gewähren!)/Zeichen 206 (Halt! Vorfahrt gewähren!) und verdeckten dieses': [],
    'Parken innerhalb eines Kreisverkehrs (Zeichen 215)': [],
    'Parken in einem Abstand von weniger als 15 Metern von einem Haltestellenschild': [
        'Parken an Haltestellen (Verkehrszeichen 224) sowie 15 Meter davor und dahinter',
        'Parken an Haltestellen sowie 15 Meter davor und dahinter'],
    'Parken, obwohl zwischen Ihrem Fahrzeug und der Fahrstreifenbegrenzung (Zeichen 295/296) ein Abstand von weniger als 3 Metern verblieb': [],
    'Parken innerhalb einer Grenzmarkierung (Zeichen 299) für ein Parkverbot': [],
    'Parken bei zulässigem Gehwegparken (Zeichen 315) nicht auf dem Gehweg': [],
    'Parken auf einem Sonderfahrstreifen für Omnibusse des Linienverkehrs (Zeichen 245)': [
        'Parkten auf einem Sonderfahrstreifen für Omnibusse des Linienverkehrs (Zeichen 245)',
        'Parken auf der Busspur'],
    'Parken auf einem gekennzeichneten Behindertenparkplatz': ['Parken auf dem Behindertenparkplatz', ],
    'Parken mit Verbrenner vor Elektroladesäule': [],
    'Parken auf einer Grünfläche': ['Parken auf Grünflächen'],
    'Parken auf einer Baumscheibe': [],
    'Parken in der Einbahnstraße entgegen der Fahrtrichtung': [],
    'Sonstiges Parkvergehen (siehe Hinweise)': [],
}

wegeheld_mapping = {
    'Parken auf einem unbeschilderten Radweg': [22],
    'Parken auf einem Fußgängerüberweg': [13],
    'Parken auf einem Radweg (Zeichen 237)': [23],
    'Parken auf einem Geh- und Radweg (Zeichen 240/241)': [],
    'Parken auf einer Fahrradstraße (Zeichen 244.1/244.2)': [],
    'Parken verbotswidrig auf einem Schutzstreifen für den Radverkehr (Zeichen 340)': [21],
    'Parken verbotswidrig auf einem Gehweg': [3],
    'Parken in einem verkehrsberuhigten Bereich (Zeichen 325.1, 325.2) verbotswidrig außerhalb der zum Parken gekennzeichneten Flächen': [],
    'Parken in einem Fußgängerbereich, der (durch Zeichen 239/242.1, 242.2/250) gesperrt war': [26],
    'Parken in einem Abstand von weniger als 5 Meter vor einem Fußgängerüberweg': [],
    'Parken weniger als 8 Meter vor der Kreuzung/Einmündung, obwohl in Fahrtrichtung rechts neben der Fahrbahn ein Radweg baulich angelegt ist': [],
    'Parken weniger als 5 Meter vor/hinter der Kreuzung/Einmündung': [15],
    'Parken im absolutem Haltverbot (Zeichen 283)': [11],
    'Parken unzulässig im eingeschränkten Haltverbot (Zeichen 286)': [12],
    'Parken unzulässig auf einer Sperrfläche (Zeichen 298)': [24],
    'Parken an einer engen/unübersichtlichen Straßenstelle': [],
    'Parken im Bereich einer scharfen Kurve': [],
    'Parken unzulässig in der zweiten Reihe': [2],
    'Parken näher als 10 Meter vor einem Lichtzeichen': [],
    'Parken vor oder in einer amtlich gekennzeichneten Feuerwehrzufahrt': [14],
    'Parken verbotswidrig im Bereich eines Taxenstandes (Zeichen 229)': [],
    'Parken verbotswidrig und verhinderten dadurch die Benutzung gekennzeichneter Parkflächen': [],
    'Parken im Bereich einer Grundstückseinfahrt bzw. -ausfahrt': [10],
    'Parken auf einer schmalen Fahrbahn gegenüber einer Grundstückseinfahrt/Grundstücks-ausfahrt': [],
    'Parken vor einer Bordsteinabsenkung': [5],
    'Parken verbotswidrig auf der linken Fahrbahnseite/dem linken Seitenstreifen': [],
    'Parken nicht am rechten Fahrbahnrand': [],
    'Parken im Fahrraum von Schienenfahrzeugen': [],
    'Parken links von einer Fahrbahnbegrenzung (Zeichen 295)': [],
    'Parken in einem Verkehrsbereich, der (durch Zeichen 250/251/253/255/260) gesperrt war': [],
    'Parken auf einem durch Richtungspfeile (Zeichen 297) gekennzeichneten Fahrbahnteil': [],
    'Parken innerhalb einer Grenzmarkierung (Zeichen 299) für ein Haltverbot': [],
    'Parken näher als 10 Meter vor einem Andreaskreuz (Zeichen 201)/Zeichen 205 (Vorfahrt gewähren!)/Zeichen 206 (Halt! Vorfahrt gewähren!) und verdeckten dieses': [],
    'Parken innerhalb eines Kreisverkehrs (Zeichen 215)': [],
    'Parken in einem Abstand von weniger als 15 Metern von einem Haltestellenschild': [6],
    'Parken, obwohl zwischen Ihrem Fahrzeug und der Fahrstreifenbegrenzung (Zeichen 295/296) ein Abstand von weniger als 3 Metern verblieb': [],
    'Parken innerhalb einer Grenzmarkierung (Zeichen 299) für ein Parkverbot': [],
    'Parken bei zulässigem Gehwegparken (Zeichen 315) nicht auf dem Gehweg': [],
    'Parken auf einem Sonderfahrstreifen für Omnibusse des Linienverkehrs (Zeichen 245)': [7],
    'Parken auf einem gekennzeichneten Behindertenparkplatz': [8],
    'Parken mit Verbrenner vor Elektroladesäule': [28],
    'Parken auf einer Grünfläche': [27],
    'Parken auf einer Baumscheibe': [],
    'Parken in der Einbahnstraße entgegen der Fahrtrichtung': [],
    'Sonstiges Parkvergehen (siehe Hinweise)': [],
}
