name: App

on:
  push:
    tags:
    - '*'

defaults:
  run:
    working-directory: wegli-android

jobs:
  build-debug-apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build debug APK
      run: bash ./gradlew assembleDebug --stacktrace
    - name: Set env
      run: echo "APK_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: weg-li-${{ env.APK_VERSION }}
        path: wegli-android/app/build/outputs/apk/debug/app-debug.apk
